apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: appassessment-app
  template: appassessment-template
message: The application assessment components have been installed into your Tools project.
metadata:
  annotations:
    description: |-
      This template deploys a suite of BCGOv application assessment components into your <LICENSE_PLATE>-tools namespace.  The two primary components are as follows:
      A cronjob that periodically surveys the <LICENSE_PLATE>-prod project, and writes the results in HTML format to a Persistent Volume Claim (pvc)
      An nginx application to serve the resulting HTML through an OpenShift route.
      NOTE: You must have admin privilege to the <LICENSE_PLATE>-tools and <LICENSE_PLATE>-prod projects to deploy this template.
    openshift.io/display-name: App Assessment Tool
  name: appassessment-app
  namespace: openshift
objects:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: ingress
    namespace: ${LICENSE_PLATE}-tools
  spec:
    ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: v1
  kind: Route
  metadata:
    name: appassessment-route
    namespace: ${LICENSE_PLATE}-tools
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: Reencrypt
    to:
      kind: Service
      name: appassessment-svc
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: appassessment-pvc
    labels:
      app: appassessment-app
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 500Mi
    volumeMode: Filesystem
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: appassessment-web
    namespace: ${LICENSE_PLATE}-tools
    labels:
      app: appassessment-app
      app.kubernetes.io/component: appassessment-web
      app.kubernetes.io/instance: appassessment-web
      app.kubernetes.io/part-of: appassessment-app
      app.openshift.io/runtime: nginx
      app.openshift.io/runtime-namespace: ${LICENSE_PLATE}-tools
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: appassessment-web
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: appassessment-web
          deploymentconfig: appassessment-web
      spec:
        serviceAccountName: appassessment-sa
        volumes:
          - name: report-out
            persistentVolumeClaim:
              claimName: appassessment-pvc
          - name: appassessment-tls
            secret:
              secretName: appassessment-tls
        containers:
          - name: appassessment-web
            image: >-
              nginxinc/nginx-unprivileged:latest
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 10m
                memory: 64Mi
            volumeMounts:
              - name: report-out
                readOnly: true
                mountPath: /usr/share/nginx/html
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
          - name: oauth-proxy 
            args:
              - --https-address=:8888
              - --provider=openshift
              - --openshift-service-account=appassessment-sa
              - --upstream=http://localhost:8080
              - --tls-cert=/etc/tls/private/tls.crt
              - --tls-key=/etc/tls/private/tls.key
              - --cookie-secret=SECRET
              - --openshift-sar={"namespace":"${LICENSE_PLATE}-tools","resource":"services","verb":"get"}
            image: quay.io/openshift/origin-oauth-proxy:4.7
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: appassessment-tls
                mountPath: /etc/tls/private
            ports:
              - name: oauth-proxy
                containerPort: 8888    
                protocol: TCP 
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: appassessment-sa
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"appassessment-route"}}'
    namespace: ${LICENSE_PLATE}-tools  
    labels:
      app: appassessment-app
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: appassessment-view
    namespace: ${LICENSE_PLATE}-prod
    labels:
      app: appassessment-app
  subjects:
  - kind: ServiceAccount
    name: appassessment-sa
    namespace: ${LICENSE_PLATE}-tools
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
- apiVersion: v1
  kind: Service
  metadata:
    name: appassessment-svc
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: appassessment-tls
    namespace: ${LICENSE_PLATE}-tools
    labels:
      app: appassessment-app
      app.kubernetes.io/component: appassessment-svc
      app.kubernetes.io/part-of: appassessment-app
  spec:
    ports:
      - name: 8888-tcp
        protocol: TCP
        port: 8888
        targetPort: 8888
    selector:
      app: appassessment-web
      deploymentconfig: appassessment-web
    type: ClusterIP
    sessionAffinity: None
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: appassessment-cj
    namespace: ${LICENSE_PLATE}-tools
    labels:
      app: appassessment-app
      app.kubernetes.io/component: appassessment-cj
      app.kubernetes.io/instance: appassessment
  spec:
    schedule: '0 0 * * 0'
    concurrencyPolicy: Allow
    suspend: false
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            serviceAccountName: appassessment-sa
            volumes:
              - name: report-out
                persistentVolumeClaim:
                  claimName: appassessment-pvc
            containers:
              - name: appassessment-cron
                image: ${APP_ASSESSMENT_IMAGE}
                env:
                  - name: TARGET_NAMESPACE
                    value: ${LICENSE_PLATE}-prod
                  - name: CLUSTER_NAME
                    value: ${CLUSTER_NAME}
                resources: {}
                volumeMounts:
                  - name: report-out
                    mountPath: /output/
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
                imagePullPolicy: Always
            restartPolicy: OnFailure
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
            securityContext: {}
            schedulerName: default-scheduler
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: initialload
    namespace: ${LICENSE_PLATE}-tools
  spec:
    parallelism: 1
    completions: 1
    backoffLimit: 6
    selector: {}
    template:
      spec:
        restartPolicy: OnFailure
        serviceAccountName: appassessment-sa
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
        containers:
          - name: appassessment-cron
            image: ${APP_ASSESSMENT_IMAGE}
            env:
              - name: TARGET_NAMESPACE
                value: ${LICENSE_PLATE}-prod
              - name: CLUSTER_NAME
                value: ${CLUSTER_NAME}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
              - name: report-out
                mountPath: /output/
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        serviceAccount: appassessment-sa
        volumes:
          - name: report-out
            persistentVolumeClaim:
              claimName: appassessment-pvc
        dnsPolicy: ClusterFirst
parameters:
- description: The six character application identifier, commonly referred to the license plate number for your application to be assessed. "example e595b8"
  displayName: Application Identifier
  name: LICENSE_PLATE
  value: "example: e595b8"
- description: The name of the Cluster in which this tool operates
  displayName: Cluster Name
  name: CLUSTER_NAME
  value: "Silver"
- description: AppAssessment image. The fully qualified image reference. 
  name: APP_ASSESSMENT_IMAGE
  value: image-registry.openshift-image-registry.svc:5000/bcgov/app-assessment
