kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: appassessment
  labels:
    app: appassessment
    app.kubernetes.io/component: appassessment
    app.kubernetes.io/instance: appassessment
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          serviceAccountName: appassessment-sa
          volumes:
            - name: report-out
              persistentVolumeClaim:
                claimName: appassessment-pvc
          containers:
            - name: appassessment
              image: >-
                image-registry.openshift-image-registry.svc:5000/7f8e79-tools/appassessment
              env:
                - name: TARGET_NAMESPACE
                  value: 7f8e79-prod
              resources: {}
              volumeMounts:
                - name: report-out
                  mountPath: /output/
                  subpath: output
              volumeMounts:
                - name: report-out
                  mountPath: /templates/
                  subpath: templates
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
